services:
  - type: web
    name: breathing
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn breathing.wsgi:application --bind 0.0.0.0:10000 --workers 2
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "breathing.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://breathing.onrender.com"

  - type: worker
    name: breathing-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        value: "https://breathing.onrender.com"
